name: Run Symfony Tests

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/app?serverVersion=16&charset=utf8
    strategy:
      matrix:
        php-version: [8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_pgsql
          ini-values: |
            memory_limit = 512M
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Run Create database
        run: php bin/console doctrine:database:create --no-interaction

      - name: Run Migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Load Fixtures
        run: php bin/console doctrine:fixtures:load --no-interaction

      - name: Run unit and functional tests
        run: php bin/phpunit --testdox --coverage-text
